#!/usr/bin/env bash
set -x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"

aws ec2 create-security-group --group-name vagrant --description 'vagrant provisioning'

my_ip=$(curl http://checkip.amazonaws.com/)
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 22 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 80 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 443 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 8080 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 8443 --cidr $my_ip/0

aws ec2 create-key-pair --key-name vagrant --query 'KeyMaterial' --output text > vagrant.pem
chmod 400 vagrant.pem

aws iam create-user --user-name vagrant
aws iam create-access-key --user-name vagrant > access-key.json
aws iam attach-user-policy --user-name vagrant --policy-arn 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'

cat > aws-variables <<'EOF'
#!/usr/bin/env bash

f=${1:-access-key.json}
[ -r "$f" ] || exit 1

export ACCESS_KEY_ID=$(jq .AccessKey.AccessKeyId "$f" | tr -d '"')
export SECRET_ACCESS_KEY=$(jq .AccessKey.SecretAccessKey "$f" | tr -d '"')
EOF

cat > Vagrantfile <<'EOF'
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-aws'
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'aws-dummy'
  config.vm.provider 'aws' do |aws, override|
    aws.access_key_id = ENV['ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
    aws.keypair_name = 'vagrant'
    aws.region = 'eu-central-1'
    aws.ami = 'ami-7c412f13'
    aws.security_groups = ['vagrant']
    aws.instance_type = 't2.micro'
    override.vm.provision "shell", path: "provision", privileged: false
    override.vm.synced_folder ".", "/vagrant", disabled: true
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = 'vagrant.pem'
  end
end
EOF

cat > provision <<'EOF'
#!/usr/bin/env bash
set -e

LOG=provision.log
op="rest-service"
log() { echo "$@" | tee -a "$LOG"; }
cd
log "Provision started ..."
log "Updating packages cache ..."
sudo apt-get -y update >> "$LOG" 2>&1
log "Installing jdk ..."
sudo apt-get -y install openjdk-8-jdk >> "$LOG" 2>&1
log "Installing $op (cloning code from git) ..."
git clone https://github.com/spring-guides/gs-rest-service.git >> "$LOG" 2>&1
log "Building $op executable jar ..."
cd gs-rest-service/complete/
./gradlew bootJar >> "$LOG" 2>&1
cd - &> /dev/null
log "Starting $op ..."
java -jar gs-rest-service/complete/build/libs/gs-rest-service-0.1.0.jar &> $op.log &
log "Provision finished with success ..."
EOF

vagrant box add aws-dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

source ./aws-variables
vagrant up

./aws-dns-name
./aws-ip-address
