#!/usr/bin/env bash
set -x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"

aws ec2 create-security-group --group-name vagrant --description 'vagrant provisioning'

my_ip=$(curl http://checkip.amazonaws.com/)
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 22 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 80 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 443 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 8080 --cidr $my_ip/0
aws ec2 authorize-security-group-ingress --group-name vagrant --protocol tcp --port 8443 --cidr $my_ip/0

aws ec2 create-key-pair --key-name vagrant --query 'KeyMaterial' --output text > vagrant.pem
chmod 400 vagrant.pem

aws iam create-user --user-name vagrant
aws iam create-access-key --user-name vagrant > access-key.json
aws iam attach-user-policy --user-name vagrant --policy-arn 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'

vagrant box add aws-dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
