#!/usr/bin/env bash
set -e

LOG=provision.log
op="gs-rest-service"

log() { echo "$@" | tee -a "$LOG"; }

cd
log "Provision started ..."

log "Updating packages cache ..."
sudo apt-get -yq update &>> "$LOG"

log "Installing utility packages ..."
sudo apt-get -yq install \
  tree \
&>> "$LOG"

log "Installing jdk ..."
sudo apt-get -yq install openjdk-8-jdk &>> "$LOG"

log "Installing $op (cloning code from git) ..."
git clone https://github.com/spring-guides/gs-rest-service.git &>> "$LOG"

log "Building $op executable jar ..."
gs-rest-service/complete/gradlew bootJar &>> "$LOG"

log "Starting $op ..."
java -jar gs-rest-service/complete/build/libs/gs-rest-service-0.1.0.jar &> $op.log &

log "Configuring port redirections ..."
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080 &>> "$LOG"
sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8443 &>> "$LOG"

log "Making iptables configurations persistent ..."
sudo sh -c "iptables-save > /etc/iptables.rules" &>> "$LOG"

# The following command is mandatory but it hangs the provision
# the workaround is to execute this inside the instance after its provision
# TODO: see how to fix this issue
#sudo apt-get -yq install iptables-persistent &>> "$LOG"

log "Provision finished with success ..."
