#!/usr/bin/env bash
set -x

cd "`dirname "$0"`"

aws ec2 delete-security-group --group-name vagrant
aws ec2 delete-key-pair --key-name vagrant
aws iam detach-user-policy --user-name vagrant --policy-arn 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
aws iam delete-access-key --user-name vagrant --access-key-id $ACCESS_KEY_ID
aws iam delete-user --user-name vagrant

rm -rf .vagrant access-key.json vagrant.pem *.log
